# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: install dependencies
        run: > 
          sudo apt-get install
          libgstreamer-1.0-dev
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
      - name: install_dependencies
        shell: msys2 {0}
        run: > 
          pacman -S --noconfirm
          mingw-w64-x86_64-cmake 
          mingw-w64-x86_64-gtkmm3
          mingw-w64-x86_64-gstreamer
          mingw-w64-x86_64-gst-plugins-good
          mingw-w64-x86_64-gst-plugins-bad
          mingw-w64-x86_64-gst-plugins-ugly
          mingw-w64-x86_64-spdlog
          mingw-w64-x86_64-aravis
          mingw-w64-x86_64-aravis-gst
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-pkg-config
      - name: checkout
        uses: actions/checkout@v6.0.1
      - name: configure cmake
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=release
      - name: build
        shell: msys2 {0}
        run: |
          cd build
          ninja
      - name: upload_build_directory
        uses: actions/upload-artifact@v5.0.0
        with:
          name: build-windows
          path: ./build/
