# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        environment: 
         - os: windows-latest
           shell: msys2 {0}
         - os: ubuntu-latest
           shell: bash
        build_type: [debug,release]
    defaults:
      run:
        shell: ${{matrix.environment.shell}}
    runs-on: ${{matrix.environment.os}}
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Setup Environment
        uses: ./.github/actions/install-deps
        with:
          os: ${{matrix.environment.os}}
      - name: configure cmake
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: build
        run: | 
          cd build
          ninja
      - name: test
        run: |
            cd build
            ctest --output-on-failure --stop-on-failure
      - name: upload_build_directory
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ${{matrix.environment.os}}-${{matrix.build_type}}
          path: ./build/
